python implement_efficiency_cluster_gpt2.py --sample 0 --groups 10
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 20
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 30
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 40
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 50
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 60
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 70
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 80
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 90
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 100
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 110
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 120
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 130
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 140
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 150
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 160
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 170
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 180
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 190
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 200
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 210
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 220
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 230
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 240
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 250
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 260
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 270
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 280
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 290
python implement_efficiency_cluster_gpt2.py --sample 0 --groups 300
