python implement_efficiency_group_gpt2.py --sample 200
python implement_efficiency_group_gpt2.py --sample 210
python implement_efficiency_group_gpt2.py --sample 220
python implement_efficiency_group_gpt2.py --sample 230
python implement_efficiency_group_gpt2.py --sample 240
python implement_efficiency_group_gpt2.py --sample 250
python implement_efficiency_group_gpt2.py --sample 260
python implement_efficiency_group_gpt2.py --sample 270
python implement_efficiency_group_gpt2.py --sample 280
python implement_efficiency_group_gpt2.py --sample 290
python implement_efficiency_group_gpt2.py --sample 300
python implement_efficiency_group_gpt2.py --sample 310
python implement_efficiency_group_gpt2.py --sample 320
python implement_efficiency_group_gpt2.py --sample 330
python implement_efficiency_group_gpt2.py --sample 340
python implement_efficiency_group_gpt2.py --sample 350
python implement_efficiency_group_gpt2.py --sample 360
python implement_efficiency_group_gpt2.py --sample 370
python implement_efficiency_group_gpt2.py --sample 380
python implement_efficiency_group_gpt2.py --sample 390
python implement_efficiency_group_gpt2.py --sample 400
python implement_efficiency_group_gpt2.py --sample 410
python implement_efficiency_group_gpt2.py --sample 420
python implement_efficiency_group_gpt2.py --sample 430
